# @format

name: data_collector
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  gap: ^3.0.1
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  uuid: ^4.3.3
  bloc: ^8.1.2
  animated_custom_dropdown: ^3.0.0
  flutter_file_dialog: ^3.0.2
  path_provider: ^2.1.2
  system_info_plus: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appicon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
